In [1]:
[1,2,3]*3

[1, 2, 3, 1, 2, 3, 1, 2, 3]

# Numerical Python (Numpy)

In [2]:
import numpy as np

In [3]:
a = np.array([1,2,3])
a

array([1, 2, 3])

In [4]:
a*3

array([3, 6, 9])

In [5]:
np.sum(a)

6

# arange, linspace, logspace

In [6]:
np.arange(0,5)

array([0, 1, 2, 3, 4])

In [7]:
np.arange(0,5,1.5)

array([0. , 1.5, 3. , 4.5])

In [8]:
np.linspace(0,10,5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [10]:
np.linspace(0,6,3)

array([0., 3., 6.])

In [11]:
np.logspace(-3,3,7)

array([1.e-03, 1.e-02, 1.e-01, 1.e+00, 1.e+01, 1.e+02, 1.e+03])

# Random

In [14]:
np.random.rand()

0.9403266998052769

In [18]:
np.random.rand(3,2)

array([[0.81074528, 0.09807071],
       [0.708839  , 0.78364762],
       [0.21399155, 0.37176005]])

# Controlled Randomness

In [23]:
state = np.random.RandomState(42)
state.rand(3)

array([0.37454012, 0.95071431, 0.73199394])